name: CI/CD Pull Latest Code and Deploy to AWS EC2

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY}}" > debug_key.pem
          chmod 600 debug_key.pem
          ssh-keygen -lf debug_key.pem || echo "Invalid key format"

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2 instance
        run: |
          ssh -T -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            cd loopster  # Replace with your actual path
            git reset --hard HEAD
            git clean -fd
            git pull origin main
            cd back-end

            if ! command -v npm &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi
            if ! command -v pm2 &> /dev/null; then
              sudo npm install -g pm2
            fi

            if [[ ! -d "node_modules" || $(git diff --name-only origin/main | grep package.json) ]]; then
              npm install
            fi
            if [[ $(git diff --name-only origin/main | grep -E '\.(js|ts|jsx|tsx)$') ]]; then
              npm run build
            fi

            pm2 restart all
            pm2 status
          EOF